[package]
name = "ammo-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0"

[build-dependencies]
cmake = "0.1.54"
cxx-build = "1.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
